// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Test1', async function() {
    await driver.get("https://dsssb.delhi.gov.in/")
    await driver.manage().window().setRect({ width: 830, height: 826 })
    await driver.findElement(By.linkText("View")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.linkText("Download")).click()
    vars["win3747"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["root"])
    await driver.close()
  })
})
